import { ToolEntry, FAQ } from './types';

const GLOBAL_FAQS: FAQ[] = [
    {
        question: "Is Tools Repository completely free to use?",
        answer: "Yes! All tools on Tools Repository are 100% free with no hidden charges, subscriptions, or premium tiers. We aim to provide high-quality utilities for everyone."
    },
    {
        question: "Is my data secure when using these tools?",
        answer: "Absolutely. Your privacy is our priority. Most of our tools are 100% client-side, meaning your data never leaves your browser. For the few that require server processing, we do not store your inputs or results."
    },
    {
        question: "Do I need to sign up or create an account?",
        answer: "No account is required. You can use any tool immediately without providing any personal information or signing in."
    }
];

const CATEGORY_FAQS: Record<string, FAQ[]> = {
    calculators: [
        {
            question: "How accurate are the calculator results?",
            answer: "Our calculators use industry-standard formulas and high-precision math libraries to ensure accuracy. However, they should be used for informational purposes only."
        },
        {
            question: "Can I use these calculators for official financial planning?",
            answer: "While highly accurate, we recommend consulting with a professional for critical financial or legal decisions."
        }
    ],
    text: [
        {
            question: "Is there a limit to how much text I can process?",
            answer: "Most tools can handle very large blocks of text (up to several megabytes). Browser performance is typically the only limit."
        },
        {
            question: "Will my text formatting be preserved?",
            answer: "It depends on the specific tool. Most text transformation tools will clearly indicate if they strip formatting or maintain it."
        }
    ],
    security: [
        {
            question: "Are the generated passwords truly random?",
            answer: "Yes, we use cryptographically secure random number generators (CSPRNG) available in modern browsers to ensure maximum security."
        },
        {
            question: "Should I trust this site for sensitive data?",
            answer: "Since the encryption and generation happen locally in your browser, your sensitive data is never transmitted to our servers."
        }
    ],
    developer: [
        {
            question: "Is the generated code optimized for performance?",
            answer: "Yes, our developer tools follow best practices to ensure the output is clean, efficient, and ready for production use."
        },
        {
            question: "Are the generated assets free for commercial use?",
            answer: "All outputs generated by our tools (SVG blobs, gradients, code snippets) are yours to use freely in both personal and commercial projects."
        }
    ],
    productivity: [
        {
            question: "Will my progress be saved if I close the tab?",
            answer: "Tools like the Habit Tracker or To-Do List use LocalStorage to save your data on your device, so it stays even after a refresh."
        },
        {
            question: "Can I use these tools offline?",
            answer: "Once the page is loaded, many of our productivity tools function perfectly without an active internet connection."
        }
    ],
    health: [
        {
            question: "Are the health results scientifically accurate?",
            answer: "We use widely accepted medical formulas (like BMI or BMR). However, these are general estimates and do not replace professional medical advice."
        },
        {
            question: "Does the app store my health metrics?",
            answer: "No. All health-related calculations are private and happen only on your device. We do not track or store your physical metrics."
        }
    ],
    converters: [
        {
            question: "Are the conversion units standardized?",
            answer: "Yes, we use the International System of Units (SI) and other recognized standard conversion factors."
        },
        {
            question: "Do you support all global measurement systems?",
            answer: "We support Metric, Imperial, and common US Customary units for maximum compatibility."
        }
    ]
};

export const HOME_FAQS: FAQ[] = [
    {
        question: "What is Tools Repository?",
        answer: "Tools Repository is a comprehensive collection of over 100 free, online utility tools designed to simplify your daily digital tasks. From text formatting and calculators to developer utilities and health trackers, we have it all."
    },
    {
        question: "How many tools are currently available on Tools Repository?",
        answer: "We currently offer over 102 premium tools across various categories, and we are constantly adding new ones based on user feedback."
    },
    {
        question: "Are these tools really free to use?",
        answer: "Yes, every single tool on our platform is completely free. We do not require any payments, subscriptions, or hidden fees."
    },
    {
        question: "Is it safe to use Tools Repository for sensitive information?",
        answer: "Yes. Most of our tools process data locally in your browser, meaning your sensitive information never touches our servers. Your privacy and security are our top priorities."
    },
    {
        question: "Can I use the outputs from these tools commercially?",
        answer: "Absolutely! Any code, gradient, SVG, or text result generated here is free to use for both personal and commercial projects."
    },
    {
        question: "Do I need to install any software to use these tools?",
        answer: "No installation is required. All tools run directly in your web browser on any device, including smartphones, tablets, and computers."
    },
    {
        question: "How often do you add new tools?",
        answer: "We frequently update our registry and add new tools. If you have a suggestion for a new tool, feel free to contact us!"
    }
];

export function getToolFAQs(tool: ToolEntry): FAQ[] {
    const specific: FAQ[] = [
        {
            question: `How do I use the ${tool.name}?`,
            answer: `Using the ${tool.name} is simple. Just provide the required inputs in the fields above, and the tool will instantly generate the results for you. Most tools work in real-time.`
        },
        {
            question: `Is the ${tool.name} mobile-friendly?`,
            answer: `Yes! Like all tools on Tools Repository, the ${tool.name} is fully responsive and works perfectly on smartphones and tablets.`
        }
    ];

    const categorySpecific = CATEGORY_FAQS[tool.category] || [];

    return [
        ...specific,
        ...categorySpecific,
        ...GLOBAL_FAQS
    ].slice(0, 7);
}
