import { ToolEntry, CategoryInfo } from './types';

export const categories: CategoryInfo[] = [
    { id: 'text', name: 'Text Tools', icon: '📄', color: 'text' },
    { id: 'calculators', name: 'Calculators', icon: '🔢', color: 'calculators' },
    { id: 'security', name: 'Security & Random', icon: '🔐', color: 'security' },
    { id: 'developer', name: 'Developer Tools', icon: '🎨', color: 'developer' },
    { id: 'converters', name: 'Unit Converters', icon: '📏', color: 'converters' },
    { id: 'productivity', name: 'Productivity', icon: '⏱️', color: 'productivity' },
    { id: 'health', name: 'Health & Fitness', icon: '❤️', color: 'health' },
];

export const tools: ToolEntry[] = [
    // ─── TEXT TOOLS ───────────────────────────
    {
        id: 'word-counter',
        name: 'Word Counter',
        slug: 'word-counter',
        category: 'text',
        icon: '📝',
        description: 'Count words, sentences, and paragraphs in your text instantly.',
        keywords: ['word count', 'text analysis', 'character count'],
        module: () => import('./tools/text/word-counter'),
    },
    {
        id: 'character-counter',
        name: 'Character Counter',
        slug: 'character-counter',
        category: 'text',
        icon: '🔤',
        description: 'Count characters with and without spaces in any text.',
        keywords: ['character count', 'letter count', 'text length'],
        module: () => import('./tools/text/character-counter'),
    },
    {
        id: 'case-converter',
        name: 'Case Converter',
        slug: 'case-converter',
        category: 'text',
        icon: '🔡',
        description: 'Convert text to uppercase, lowercase, title case, and more.',
        keywords: ['uppercase', 'lowercase', 'title case', 'capitalize'],
        module: () => import('./tools/text/case-converter'),
    },
    {
        id: 'remove-extra-spaces',
        name: 'Remove Extra Spaces',
        slug: 'remove-extra-spaces',
        category: 'text',
        icon: '✂️',
        description: 'Clean up text by removing extra whitespace and blank lines.',
        keywords: ['whitespace', 'trim', 'clean text'],
        module: () => import('./tools/text/remove-extra-spaces'),
    },
    {
        id: 'text-reverser',
        name: 'Text Reverser',
        slug: 'text-reverser',
        category: 'text',
        icon: '🔄',
        description: 'Reverse any text, words, or individual characters.',
        keywords: ['reverse text', 'flip text', 'mirror text'],
        module: () => import('./tools/text/text-reverser'),
    },
    {
        id: 'palindrome-checker',
        name: 'Palindrome Checker',
        slug: 'palindrome-checker',
        category: 'text',
        icon: '🪞',
        description: 'Check if a word or phrase reads the same forwards and backwards.',
        keywords: ['palindrome', 'word checker', 'reverse match'],
        module: () => import('./tools/text/palindrome-checker'),
    },
    {
        id: 'json-formatter',
        name: 'JSON Formatter & Validator',
        slug: 'json-formatter',
        category: 'text',
        icon: '📋',
        description: 'Format, validate, and beautify your JSON data.',
        keywords: ['json format', 'json validate', 'json beautify'],
        module: () => import('./tools/text/json-formatter'),
    },
    {
        id: 'lorem-ipsum-generator',
        name: 'Lorem Ipsum Generator',
        slug: 'lorem-ipsum-generator',
        category: 'text',
        icon: '📜',
        description: 'Generate placeholder Lorem Ipsum text for design mockups.',
        keywords: ['lorem ipsum', 'dummy text', 'placeholder text'],
        module: () => import('./tools/text/lorem-ipsum-generator'),
    },
    {
        id: 'text-to-slug',
        name: 'Text to Slug Converter',
        slug: 'text-to-slug',
        category: 'text',
        icon: '🔗',
        description: 'Convert text into URL-friendly slugs instantly.',
        keywords: ['slug', 'url friendly', 'permalink'],
        module: () => import('./tools/text/text-to-slug'),
    },
    {
        id: 'duplicate-line-remover',
        name: 'Duplicate Line Remover',
        slug: 'duplicate-line-remover',
        category: 'text',
        icon: '🗑️',
        description: 'Remove duplicate lines from text while preserving order.',
        keywords: ['remove duplicates', 'unique lines', 'dedup'],
        module: () => import('./tools/text/duplicate-line-remover'),
    },
    {
        id: 'binary-converter',
        name: 'Binary Converter',
        slug: 'binary-converter',
        category: 'text',
        icon: '🔢',
        description: 'Convert text to binary and binary back to plain text.',
        keywords: ['binary', 'encoding', 'decoder', '0101'],
        module: () => import('./tools/text/binary-converter'),
    },
    {
        id: 'morse-code-converter',
        name: 'Morse Code Converter',
        slug: 'morse-code-converter',
        category: 'text',
        icon: '⠓',
        description: 'Encode and decode Morse code messages instantly.',
        keywords: ['morse', 'telegraph', 'signal'],
        module: () => import('./tools/text/morse-code-converter'),
    },
    {
        id: 'list-sorter',
        name: 'List Sorter',
        slug: 'list-sorter',
        category: 'text',
        icon: '↕️',
        description: 'Sort your lists alphabetically, numerically, or in reverse.',
        keywords: ['sort', 'alphabetize', 'order'],
        module: () => import('./tools/text/list-sorter'),
    },
    {
        id: 'markdown-previewer',
        name: 'Markdown Previewer',
        slug: 'markdown-previewer',
        category: 'text',
        icon: '📉',
        description: 'Write Markdown and see the rendered HTML preview instantly.',
        keywords: ['markdown', 'preview', 'editor', 'render'],
        module: () => import('./tools/text/markdown-previewer'),
    },
    {
        id: 'text-diff-checker',
        name: 'Text Diff Checker',
        slug: 'text-diff-checker',
        category: 'text',
        icon: '🔍',
        description: 'Compare two blocks of text and see the differences side-by-side.',
        keywords: ['diff', 'compare', 'text difference'],
        module: () => import('./tools/text/text-diff-checker'),
    },
    {
        id: 'csv-to-json',
        name: 'CSV to JSON Converter',
        slug: 'csv-to-json',
        category: 'text',
        icon: '📊',
        description: 'Convert CSV data into clean, structured JSON objects.',
        keywords: ['csv', 'json', 'convert', 'data'],
        module: () => import('./tools/text/csv-to-json'),
    },
    {
        id: 'json-to-csv',
        name: 'JSON to CSV Converter',
        slug: 'json-to-csv',
        category: 'text',
        icon: '📑',
        description: 'Convert JSON arrays into flat CSV files for spreadsheets.',
        keywords: ['json', 'csv', 'convert', 'data'],
        module: () => import('./tools/text/json-to-csv'),
    },
    {
        id: 'yaml-to-json',
        name: 'YAML to JSON Converter',
        slug: 'yaml-to-json',
        category: 'text',
        icon: '⚙️',
        description: 'Switch between YAML and JSON configuration formats easily.',
        keywords: ['yaml', 'json', 'convert', 'config'],
        module: () => import('./tools/text/yaml-to-json'),
    },
    {
        id: 'nato-phonetic',
        name: 'Text to NATO Phonetic',
        slug: 'nato-phonetic',
        category: 'text',
        icon: '✈️',
        description: 'Convert text into the NATO phonetic alphabet (Alpha, Bravo...).',
        keywords: ['nato', 'phonetic', 'alphabet', 'communication'],
        module: () => import('./tools/text/nato-phonetic'),
    },
    {
        id: 'sentiment-analyzer',
        name: 'Sentiment Analyzer',
        slug: 'sentiment-analyzer',
        category: 'text',
        icon: '😊',
        description: 'Analyze the tone of your text (Positive, Negative, Neutral).',
        keywords: ['sentiment', 'tone', 'analysis', 'emotion'],
        module: () => import('./tools/text/sentiment-analyzer'),
    },
    {
        id: 'rot13-encoder',
        name: 'ROT13 Encoder/Decoder',
        slug: 'rot13-encoder',
        category: 'text',
        icon: '🔑',
        description: 'Encode or decode text using the ROT13 substitution cipher.',
        keywords: ['rot13', 'cipher', 'encode', 'decode'],
        module: () => import('./tools/text/rot13-encoder'),
    },
    {
        id: 'zalgo-text-generator',
        name: 'Zalgo Text Generator',
        slug: 'zalgo-text-generator',
        category: 'text',
        icon: '👻',
        description: 'Generate creepy, glitchy Zalgo text for social media.',
        keywords: ['zalgo', 'glitch', 'creepy', 'text style'],
        module: () => import('./tools/text/zalgo-text-generator'),
    },
    {
        id: 'upside-down-text',
        name: 'Upside Down Text',
        slug: 'upside-down-text',
        category: 'text',
        icon: '🙃',
        description: 'Flip your text upside down instantly.',
        keywords: ['upside down', 'flip', 'reverse'],
        module: () => import('./tools/text/upside-down-text'),
    },
    {
        id: 'text-to-speech',
        name: 'Text to Speech',
        slug: 'text-to-speech',
        category: 'text',
        icon: '🗣️',
        description: 'Convert text into spoken audio using browser voices.',
        keywords: ['tts', 'speech', 'voice', 'read aloud'],
        module: () => import('./tools/text/text-to-speech'),
    },
    {
        id: 'email-extractor',
        name: 'Email Extractor',
        slug: 'email-extractor',
        category: 'text',
        icon: '📧',
        description: 'Extract all email addresses from a block of text instantly.',
        keywords: ['email', 'extract', 'scrape', 'finder'],
        module: () => import('./tools/text/email-extractor'),
    },

    // ─── CALCULATOR TOOLS ───────────────────────
    {
        id: 'basic-calculator',
        name: 'Basic Calculator',
        slug: 'basic-calculator',
        category: 'calculators',
        icon: '➕',
        description: 'A simple, clean calculator for everyday arithmetic.',
        keywords: ['calculator', 'math', 'add', 'subtract', 'multiply', 'divide'],
        module: () => import('./tools/calculators/basic-calculator'),
    },
    {
        id: 'percentage-calculator',
        name: 'Percentage Calculator',
        slug: 'percentage-calculator',
        category: 'calculators',
        icon: '💹',
        description: 'Calculate percentages, percentage changes, and more.',
        keywords: ['percentage', 'percent', 'ratio'],
        module: () => import('./tools/calculators/percentage-calculator'),
    },
    {
        id: 'age-calculator',
        name: 'Age Calculator',
        slug: 'age-calculator',
        category: 'calculators',
        icon: '🎂',
        description: 'Calculate your exact age in years, months, and days.',
        keywords: ['age', 'birthday', 'date difference'],
        module: () => import('./tools/calculators/age-calculator'),
    },
    {
        id: 'bmi-calculator',
        name: 'BMI Calculator',
        slug: 'bmi-calculator',
        category: 'calculators',
        icon: '⚖️',
        description: 'Calculate your Body Mass Index and health category.',
        keywords: ['bmi', 'body mass index', 'health', 'weight'],
        module: () => import('./tools/calculators/bmi-calculator'),
    },
    {
        id: 'discount-calculator',
        name: 'Discount Calculator',
        slug: 'discount-calculator',
        category: 'calculators',
        icon: '🏷️',
        description: 'Calculate discount amounts and final prices instantly.',
        keywords: ['discount', 'sale', 'savings', 'price'],
        module: () => import('./tools/calculators/discount-calculator'),
    },
    {
        id: 'loan-emi-calculator',
        name: 'Loan EMI Calculator',
        slug: 'loan-emi-calculator',
        category: 'calculators',
        icon: '🏦',
        description: 'Calculate monthly EMI for any loan with detailed breakdown.',
        keywords: ['emi', ' loan', 'mortgage', 'interest'],
        module: () => import('./tools/calculators/loan-emi-calculator'),
    },
    {
        id: 'scientific-calculator',
        name: 'Scientific Calculator',
        slug: 'scientific-calculator',
        category: 'calculators',
        icon: '🧪',
        description: 'Advanced calculator with trigonometric and scientific functions.',
        keywords: ['scientific', 'sin', 'cos', 'tan', 'logarithm', 'square root'],
        module: () => import('./tools/calculators/scientific-calculator'),
    },
    {
        id: 'time-duration-calculator',
        name: 'Time Duration Calculator',
        slug: 'time-duration-calculator',
        category: 'calculators',
        icon: '⏱️',
        description: 'Calculate the duration between two dates or times.',
        keywords: ['time', 'duration', 'date difference', 'hours'],
        module: () => import('./tools/calculators/time-duration-calculator'),
    },
    {
        id: 'tip-calculator',
        name: 'Tip Calculator',
        slug: 'tip-calculator',
        category: 'calculators',
        icon: '💸',
        description: 'Calculate tips and split the bill easily among friends.',
        keywords: ['tip', 'split bill', 'restaurant', 'gratuity'],
        module: () => import('./tools/calculators/tip-calculator'),
    },
    {
        id: 'compound-interest-calculator',
        name: 'Compound Interest Calculator',
        slug: 'compound-interest-calculator',
        category: 'calculators',
        icon: '📈',
        description: 'Calculate how your savings grow over time with compound interest.',
        keywords: ['compound interest', 'investment', 'savings', 'interest'],
        module: () => import('./tools/calculators/compound-interest-calculator'),
    },
    {
        id: 'bmr-calculator',
        name: 'BMR Calculator',
        slug: 'bmr-calculator',
        category: 'calculators',
        icon: '🥗',
        description: 'Calculate your Basal Metabolic Rate and daily calorie needs.',
        keywords: ['bmr', 'calories', 'metabolism', 'fitness'],
        module: () => import('./tools/calculators/bmr-calculator'),
    },
    {
        id: 'sales-tax-calculator',
        name: 'Sales Tax Calculator',
        slug: 'sales-tax-calculator',
        category: 'calculators',
        icon: '🧾',
        description: 'Calculate sales tax, total price, and pre-tax amounts.',
        keywords: ['tax', 'sales tax', 'vat', 'price'],
        module: () => import('./tools/calculators/sales-tax-calculator'),
    },
    {
        id: 'savings-goal-calculator',
        name: 'Savings Goal Calculator',
        slug: 'savings-goal-calculator',
        category: 'calculators',
        icon: '💰',
        description: 'Plan your savings to reach a specific financial goal.',
        keywords: ['savings', 'finance', 'goal', 'money'],
        module: () => import('./tools/calculators/savings-goal-calculator'),
    },
    {
        id: 'fuel-cost-calculator',
        name: 'Fuel Cost Calculator',
        slug: 'fuel-cost-calculator',
        category: 'calculators',
        icon: '⛽',
        description: 'Calculate trip fuel costs based on distance and MPG.',
        keywords: ['fuel', 'gas', 'trip', 'travel'],
        module: () => import('./tools/calculators/fuel-cost-calculator'),
    },
    {
        id: 'gpa-calculator',
        name: 'GPA Calculator',
        slug: 'gpa-calculator',
        category: 'calculators',
        icon: '🎓',
        description: 'Calculate your semester GPA using letter grades and credits.',
        keywords: ['gpa', 'grades', 'student', 'education', 'letter grades'],
        module: () => import('./tools/calculators/gpa-calculator'),
    },
    {
        id: 'cgpa-calculator',
        name: 'CGPA Calculator',
        slug: 'cgpa-calculator',
        category: 'calculators',
        icon: '📊',
        description: 'Calculate your Cumulative GPA (CGPA) based on semester GPAs.',
        keywords: ['cgpa', 'cumulative gpa', 'semester', 'education'],
        module: () => import('./tools/calculators/cgpa-calculator'),
    },
    {
        id: 'auto-loan-calculator',
        name: 'Auto Loan Calculator',
        slug: 'auto-loan-calculator',
        category: 'calculators',
        icon: '🚗',
        description: 'Calculate monthly car payments and total interest.',
        keywords: ['car loan', 'auto', 'finance', 'payment'],
        module: () => import('./tools/calculators/auto-loan-calculator'),
    },
    {
        id: 'mortgage-payoff-calculator',
        name: 'Mortgage Payoff Calculator',
        slug: 'mortgage-payoff-calculator',
        category: 'calculators',
        icon: '🏠',
        description: 'See how extra payments can shorten your mortgage.',
        keywords: ['mortgage', 'loan', 'payoff', 'finance'],
        module: () => import('./tools/calculators/mortgage-payoff-calculator'),
    },
    {
        id: 'unix-timestamp-converter',
        name: 'Unix Timestamp Converter',
        slug: 'unix-timestamp-converter',
        category: 'calculators',
        icon: '🕒',
        description: 'Convert Unix timestamps to human dates and vice versa.',
        keywords: ['unix', 'timestamp', 'epoch', 'time'],
        module: () => import('./tools/calculators/unix-timestamp-converter'),
    },
    {
        id: 'base-converter',
        name: 'Base Converter',
        slug: 'base-converter',
        category: 'calculators',
        icon: '🔢',
        description: 'Convert numbers between Binary, Decimal, Hex, and Octal.',
        keywords: ['binary', 'hex', 'decimal', 'base'],
        module: () => import('./tools/calculators/base-converter'),
    },
    {
        id: 'aspect-ratio-calculator',
        name: 'Aspect Ratio Calculator',
        slug: 'aspect-ratio-calculator',
        category: 'calculators',
        icon: '🖼️',
        description: 'Calculate image and video dimensions for any aspect ratio.',
        keywords: ['aspect ratio', 'dimension', 'image', 'video'],
        module: () => import('./tools/calculators/aspect-ratio-calculator'),
    },
    {
        id: 'date-difference-calculator',
        name: 'Date Difference Calculator',
        slug: 'date-difference-calculator',
        category: 'calculators',
        icon: '📅',
        description: 'Find the exact time difference between two dates.',
        keywords: ['date', 'time', 'difference', 'days'],
        module: () => import('./tools/calculators/date-difference-calculator'),
    },
    {
        id: 'inflation-calculator',
        name: 'Inflation Calculator',
        slug: 'inflation-calculator',
        category: 'calculators',
        icon: '💸',
        description: 'Estimate the value of money over time due to inflation.',
        keywords: ['inflation', 'money', 'value', 'finance'],
        module: () => import('./tools/calculators/inflation-calculator'),
    },

    // ─── SECURITY & RANDOM TOOLS ────────────────
    {
        id: 'password-generator',
        name: 'Password Generator',
        slug: 'password-generator',
        category: 'security',
        icon: '🔑',
        description: 'Generate strong, secure passwords with custom options.',
        keywords: ['password', 'security', 'strong password', 'random'],
        module: () => import('./tools/security/password-generator'),
    },
    {
        id: 'password-strength-checker',
        name: 'Password Strength',
        slug: 'password-strength-checker',
        category: 'security',
        icon: '🛡️',
        description: 'Check how strong your password is and its estimated crack time.',
        keywords: ['password checker', 'password strength', 'security tester'],
        module: () => import('./tools/security/password-strength-checker'),
    },
    {
        id: 'random-number-generator',
        name: 'Random Number Generator',
        slug: 'random-number-generator',
        category: 'security',
        icon: '🎲',
        description: 'Generate random numbers within a specified range.',
        keywords: ['random number', 'rng', 'dice', 'random'],
        module: () => import('./tools/security/random-number-generator'),
    },
    {
        id: 'random-name-picker',
        name: 'Random Name Picker',
        slug: 'random-name-picker',
        category: 'security',
        icon: '🎯',
        description: 'Pick random names or items from a list for raffles and decisions.',
        keywords: ['random picker', 'raffle', 'lottery', 'name picker'],
        module: () => import('./tools/security/random-name-picker'),
    },
    {
        id: 'uuid-generator',
        name: 'UUID Generator',
        slug: 'uuid-generator',
        category: 'security',
        icon: '🆔',
        description: 'Generate universally unique identifiers (UUID v4) instantly.',
        keywords: ['uuid', 'guid', 'unique id'],
        module: () => import('./tools/security/uuid-generator'),
    },
    {
        id: 'qr-code-generator',
        name: 'QR Code Generator',
        slug: 'qr-code-generator',
        category: 'security',
        icon: '📱',
        description: 'Generate QR codes for URLs, text, or any data.',
        keywords: ['qr code', 'barcode', 'scan'],
        module: () => import('./tools/security/qr-code-generator'),
    },
    {
        id: 'color-palette-generator',
        name: 'Color Palette Generator',
        slug: 'color-palette-generator',
        category: 'security',
        icon: '🎨',
        description: 'Generate beautiful, harmonious color palettes.',
        keywords: ['color palette', 'colors', 'design', 'scheme'],
        module: () => import('./tools/security/color-palette-generator'),
    },
    {
        id: 'sha256-hash',
        name: 'SHA-256 Hash Generator',
        slug: 'sha256-hash',
        category: 'security',
        icon: '🔒',
        description: 'Generate secure SHA-256 hashes for any text string.',
        keywords: ['sha256', 'hash', 'security', 'crypto'],
        module: () => import('./tools/security/sha256-hash'),
    },
    {
        id: 'md5-hash',
        name: 'MD5 Hash Generator',
        slug: 'md5-hash',
        category: 'security',
        icon: '🔐',
        description: 'Generate MD5 hashes for text quickly.',
        keywords: ['md5', 'hash', 'security'],
        module: () => import('./tools/security/md5-hash'),
    },
    {
        id: 'coin-flip-dice',
        name: 'Coin Flip & Dice Roller',
        slug: 'coin-flip-dice',
        category: 'security',
        icon: '🪙',
        description: 'Flip a coin or roll dice for quick decisions.',
        keywords: ['coin flip', 'dice', 'random', 'chance'],
        module: () => import('./tools/security/coin-flip-dice'),
    },
    {
        id: 'random-string-generator',
        name: 'Random String Generator',
        slug: 'random-string-generator',
        category: 'security',
        icon: '🔣',
        description: 'Generate random alphanumeric strings with custom length.',
        keywords: ['random string', 'token', 'id'],
        module: () => import('./tools/security/random-string-generator'),
    },

    // ─── DEVELOPER TOOLS ────────────────────────
    {
        id: 'base64-encode-decode',
        name: 'Base64 Encode/Decode',
        slug: 'base64-encode-decode',
        category: 'developer',
        icon: '🔐',
        description: 'Encode text to Base64 or decode Base64 to plain text.',
        keywords: ['base64', 'encode', 'decode', 'encoding'],
        module: () => import('./tools/developer/base64-encode-decode'),
    },
    {
        id: 'url-encoder-decoder',
        name: 'URL Encoder/Decoder',
        slug: 'url-encoder-decoder',
        category: 'developer',
        icon: '🌐',
        description: 'Encode or decode URL components safely.',
        keywords: ['url encode', 'url decode', 'percent encoding'],
        module: () => import('./tools/developer/url-encoder-decoder'),
    },
    {
        id: 'html-minifier',
        name: 'HTML Minifier',
        slug: 'html-minifier',
        category: 'developer',
        icon: '📄',
        description: 'Minify HTML by removing whitespace and comments.',
        keywords: ['html minify', 'compress html', 'minification'],
        module: () => import('./tools/developer/html-minifier'),
    },
    {
        id: 'css-minifier',
        name: 'CSS Minifier',
        slug: 'css-minifier',
        category: 'developer',
        icon: '🎨',
        description: 'Minify CSS by removing whitespace and comments.',
        keywords: ['css minify', 'compress css', 'minification'],
        module: () => import('./tools/developer/css-minifier'),
    },
    {
        id: 'js-minifier',
        name: 'JavaScript Minifier',
        slug: 'js-minifier',
        category: 'developer',
        icon: '⚡',
        description: 'Minify JavaScript by removing whitespace and comments.',
        keywords: ['js minify', 'compress javascript', 'minification'],
        module: () => import('./tools/developer/js-minifier'),
    },
    {
        id: 'gradient-generator',
        name: 'Gradient Generator',
        slug: 'gradient-generator',
        category: 'developer',
        icon: '🌈',
        description: 'Create beautiful CSS gradients with a visual editor.',
        keywords: ['gradient', 'css gradient', 'color gradient'],
        module: () => import('./tools/developer/gradient-generator'),
    },
    {
        id: 'box-shadow-generator',
        name: 'Box Shadow Generator',
        slug: 'box-shadow-generator',
        category: 'developer',
        icon: '🖼️',
        description: 'Generate CSS box-shadow with a live visual preview.',
        keywords: ['box shadow', 'css shadow', 'drop shadow'],
        module: () => import('./tools/developer/box-shadow-generator'),
    },
    {
        id: 'border-radius-generator',
        name: 'CSS Border Radius Generator',
        slug: 'border-radius-generator',
        category: 'developer',
        icon: '⬜',
        description: 'Generate CSS border-radius with a visual shape editor.',
        keywords: ['border radius', 'rounded corners', 'css radius'],
        module: () => import('./tools/developer/border-radius-generator'),
    },
    {
        id: 'glassmorphism-generator',
        name: 'Glassmorphism CSS Generator',
        slug: 'glassmorphism-generator',
        category: 'developer',
        icon: '💎',
        description: 'Create beautiful frosted glass effects with CSS.',
        keywords: ['glassmorphism', 'glass css', 'frosted glass'],
        module: () => import('./tools/developer/glassmorphism-generator'),
    },
    {
        id: 'svg-blob-generator',
        name: 'SVG Blob Generator',
        slug: 'svg-blob-generator',
        category: 'developer',
        icon: '🫧',
        description: 'Generate organic SVG blob shapes for your designs.',
        keywords: ['svg', 'blob', 'design', 'shape'],
        module: () => import('./tools/developer/svg-blob-generator'),
    },
    {
        id: 'flexbox-generator',
        name: 'CSS Flexbox Generator',
        slug: 'flexbox-generator',
        category: 'developer',
        icon: '📦',
        description: 'Visually build and copy CSS Flexbox layout code.',
        keywords: ['flexbox', 'css', 'layout', 'generator'],
        module: () => import('./tools/developer/flexbox-generator'),
    },
    {
        id: 'grid-generator',
        name: 'CSS Grid Generator',
        slug: 'grid-generator',
        category: 'developer',
        icon: '🕸️',
        description: 'Create complex CSS Grid layouts with an interactive editor.',
        keywords: ['grid', 'css', 'layout', 'generator'],
        module: () => import('./tools/developer/grid-generator'),
    },
    {
        id: 'button-generator',
        name: 'CSS Button Generator',
        slug: 'button-generator',
        category: 'developer',
        icon: '🔘',
        description: 'Design premium-style CSS buttons with hover effects.',
        keywords: ['button', 'css', 'ui', 'generator'],
        module: () => import('./tools/developer/button-generator'),
    },
    {
        id: 'filter-effects-generator',
        name: 'CSS Filter Effects',
        slug: 'filter-effects-generator',
        category: 'developer',
        icon: '🎭',
        description: 'Apply and copy CSS filter effects for images.',
        keywords: ['filter', 'css', 'effects', 'blur'],
        module: () => import('./tools/developer/filter-effects-generator'),
    },
    {
        id: 'meta-tag-generator',
        name: 'Meta Tag Generator',
        slug: 'meta-tag-generator',
        category: 'developer',
        icon: '🏷️',
        description: 'Generate SEO and social media meta tags for your site.',
        keywords: ['meta tags', 'seo', 'social', 'og'],
        module: () => import('./tools/developer/meta-tag-generator'),
    },
    {
        id: 'json-to-ts',
        name: 'JSON to TypeScript',
        slug: 'json-to-ts',
        category: 'developer',
        icon: '🔷',
        description: 'Convert JSON objects into TypeScript interfaces.',
        keywords: ['json', 'typescript', 'interface', 'convert'],
        module: () => import('./tools/developer/json-to-ts'),
    },
    {
        id: 'contrast-checker',
        name: 'Color Contrast Checker',
        slug: 'contrast-checker',
        category: 'developer',
        icon: '👁️',
        description: 'Check color contrast for WCAG accessibility compliance.',
        keywords: ['contrast', 'a11y', 'wcag', 'color'],
        module: () => import('./tools/developer/contrast-checker'),
    },
    {
        id: 'robots-txt-generator',
        name: 'Robots.txt Generator',
        slug: 'robots-txt-generator',
        category: 'developer',
        icon: '🤖',
        description: 'Quickly create robots.txt files for search engines.',
        keywords: ['robots.txt', 'seo', 'search engine'],
        module: () => import('./tools/developer/robots-txt-generator'),
    },
    {
        id: 'sitemap-generator',
        name: 'Sitemap Generator',
        slug: 'sitemap-generator',
        category: 'developer',
        icon: '🗺️',
        description: 'Generate basic XML sitemaps for your website.',
        keywords: ['sitemap', 'xml', 'seo'],
        module: () => import('./tools/developer/sitemap-generator'),
    },
    {
        id: 'html-table-generator',
        name: 'HTML Table Generator',
        slug: 'html-table-generator',
        category: 'developer',
        icon: '📊',
        description: 'Visually build and copy HTML table code.',
        keywords: ['table', 'html', 'generator'],
        module: () => import('./tools/developer/html-table-generator'),
    },
    {
        id: 'image-to-base64',
        name: 'Image to Base64 Converter',
        slug: 'image-to-base64',
        category: 'developer',
        icon: '🖼️',
        description: 'Convert any image to a Base64 encoded string locally.',
        keywords: ['image', 'base64', 'encode', 'converter', 'data uri'],
        module: () => import('./tools/developer/image-to-base64'),
    },
    {
        id: 'base64-to-image',
        name: 'Base64 to Image',
        slug: 'base64-to-image',
        category: 'developer',
        icon: '🖼️',
        description: 'Convert a Base64 string back to a downloadable image.',
        keywords: ['base64', 'image', 'decode', 'converter'],
        module: () => import('./tools/developer/base64-to-image'),
    },

    {
        id: 'image-resizer',
        name: 'Image Resizer',
        slug: 'image-resizer',
        category: 'developer',
        icon: '📐',
        description: 'Easily resize images with aspect ratio locking.',
        keywords: ['image', 'resize', 'dimensions', 'width', 'height'],
        module: () => import('./tools/developer/image-resizer'),
    },

    // ─── PRODUCTIVITY TOOLS ─────────────────────
    {
        id: 'pomodoro-timer',
        name: 'Pomodoro Timer',
        slug: 'pomodoro-timer',
        category: 'productivity',
        icon: '🍅',
        description: 'Focus timer with customizable work and break intervals.',
        keywords: ['pomodoro', 'timer', 'focus', 'study'],
        module: () => import('./tools/productivity/pomodoro-timer'),
    },
    {
        id: 'habit-tracker',
        name: 'Simple Habit Tracker',
        slug: 'habit-tracker',
        category: 'productivity',
        icon: '📅',
        description: 'Track your daily habits and maintain your streaks.',
        keywords: ['habit', 'tracker', 'streak', 'productivity'],
        module: () => import('./tools/productivity/habit-tracker'),
    },
    {
        id: 'todo-list',
        name: 'Quick To-Do List',
        slug: 'todo-list',
        category: 'productivity',
        icon: '✅',
        description: 'Simple browser-based task manager to stay organized.',
        keywords: ['todo', 'list', 'tasks', 'productivity'],
        module: () => import('./tools/productivity/todo-list'),
    },
    {
        id: 'decision-wheel',
        name: 'Random Decision Wheel',
        slug: 'decision-wheel',
        category: 'productivity',
        icon: '🎡',
        description: 'Spin the wheel to make random decisions fun.',
        keywords: ['decision', 'wheel', 'random', 'picker'],
        module: () => import('./tools/productivity/decision-wheel'),
    },
    {
        id: 'stopwatch',
        name: 'Stopwatch & Lap Timer',
        slug: 'stopwatch',
        category: 'productivity',
        icon: '⏱️',
        description: 'High-precision stopwatch with lap timing features.',
        keywords: ['stopwatch', 'timer', 'laps', 'precision'],
        module: () => import('./tools/productivity/stopwatch'),
    },
    {
        id: 'world-clock',
        name: 'World Clock',
        slug: 'world-clock',
        category: 'productivity',
        icon: '🌍',
        description: 'Current time across major cities and time zones.',
        keywords: ['world clock', 'time zone', 'cities'],
        module: () => import('./tools/productivity/world-clock'),
    },
    {
        id: 'countdown-timer',
        name: 'Days Until Countdown',
        slug: 'countdown-timer',
        category: 'productivity',
        icon: '📅',
        description: 'Countdown to specific events, holidays, or milestones.',
        keywords: ['countdown', 'timer', 'event', 'days until'],
        module: () => import('./tools/productivity/countdown-timer'),
    },
    {
        id: 'leap-year-checker',
        name: 'Leap Year Checker',
        slug: 'leap-year-checker',
        category: 'productivity',
        icon: '🗓️',
        description: 'Quickly find out if any given year is a leap year.',
        keywords: ['leap year', 'calendar', 'year'],
        module: () => import('./tools/productivity/leap-year-checker'),
    },
    {
        id: 'morse-audio',
        name: 'Morse Code Audio',
        slug: 'morse-audio',
        category: 'productivity',
        icon: '🔊',
        description: 'Convert text into Morse code audio signals.',
        keywords: ['morse', 'audio', 'sound', 'signal'],
        module: () => import('./tools/productivity/morse-audio'),
    },
    {
        id: 'simple-scratchpad',
        name: 'Simple Scratchpad',
        slug: 'simple-scratchpad',
        category: 'productivity',
        icon: '📝',
        description: 'Autosaving notes for quick thoughts and snippets.',
        keywords: ['notes', 'scratchpad', 'text', 'save'],
        module: () => import('./tools/productivity/simple-scratchpad'),
    },
    // ─── HEALTH TOOLS ───────────────────────────
    {
        id: 'water-intake',
        name: 'Water Intake Calculator',
        slug: 'water-intake',
        category: 'health',
        icon: '💧',
        description: 'Calculate your daily hydration goal based on weight.',
        keywords: ['water', 'hydration', 'health', 'intake'],
        module: () => import('./tools/health/water-intake'),
    },
    {
        id: 'ideal-weight',
        name: 'Ideal Weight Calculator',
        slug: 'ideal-weight',
        category: 'health',
        icon: '⚖️',
        description: 'Estimate your target weight based on clinical formulas.',
        keywords: ['weight', 'ideal', 'health', 'fitness'],
        module: () => import('./tools/health/ideal-weight'),
    },
    {
        id: 'body-fat',
        name: 'Body Fat Percentage',
        slug: 'body-fat',
        category: 'health',
        icon: '📉',
        description: 'Estimate body fat using US Navy tape-measure method.',
        keywords: ['body fat', 'fitness', 'weight', 'health'],
        module: () => import('./tools/health/body-fat'),
    },
    {
        id: 'macros-calculator',
        name: 'Macros Calculator',
        slug: 'macros-calculator',
        category: 'health',
        icon: '🥩',
        description: 'Breakdown of Protein, Carbs, and Fats for your goals.',
        keywords: ['macros', 'protein', 'diet', 'nutrition'],
        module: () => import('./tools/health/macros-calculator'),
    },
    {
        id: 'running-pace',
        name: 'Running Pace Calculator',
        slug: 'running-pace',
        category: 'health',
        icon: '🏃',
        description: 'Find required pace for race distances and times.',
        keywords: ['running', 'pace', 'race', 'marathon'],
        module: () => import('./tools/health/running-pace'),
    },
    {
        id: 'interval-timer',
        name: 'Interval Timer (HIIT)',
        slug: 'interval-timer',
        category: 'health',
        icon: '⏱️',
        description: 'Timer for HIIT, workouts, and circuit training.',
        keywords: ['interval', 'hiit', 'timer', 'workout'],
        module: () => import('./tools/health/interval-timer'),
    },

    {
        id: 'steps-to-km',
        name: 'Steps to Km Converter',
        slug: 'steps-to-km',
        category: 'health',
        icon: '👣',
        description: 'Convert daily steps into distance (km and miles).',
        keywords: ['steps', 'distance', 'converter', 'walking'],
        module: () => import('./tools/health/steps-to-km'),
    },
    {
        id: 'bsa-calculator',
        name: 'BSA Calculator',
        slug: 'bsa-calculator',
        category: 'health',
        icon: '🧬',
        description: 'Calculate Body Surface Area based on height and weight.',
        keywords: ['bsa', 'body surface area', 'medical', 'health'],
        module: () => import('./tools/health/bsa-calculator'),
    },

    // ─── UNIT CONVERTERS ────────────────────────
    {
        id: 'length-converter',
        name: 'Length Converter',
        slug: 'length-converter',
        category: 'converters',
        icon: '📏',
        description: 'Convert between meters, feets, inches, and other length units.',
        keywords: ['length', 'distance', 'converter', 'unit'],
        module: () => import('./tools/converters/length-converter'),
    },
    {
        id: 'weight-converter',
        name: 'Weight Converter',
        slug: 'weight-converter',
        category: 'converters',
        icon: '⚖️',
        description: 'Convert between kilograms, pounds, and other weight units.',
        keywords: ['weight', 'mass', 'converter', 'unit'],
        module: () => import('./tools/converters/weight-converter'),
    },
    {
        id: 'temperature-converter',
        name: 'Temperature Converter',
        slug: 'temperature-converter',
        category: 'converters',
        icon: '🌡️',
        description: 'Convert between Celsius, Fahrenheit, and Kelvin.',
        keywords: ['temperature', 'celsius', 'fahrenheit', 'unit'],
        module: () => import('./tools/converters/temperature-converter'),
    },
    {
        id: 'digital-data-converter',
        name: 'Digital Data Converter',
        slug: 'digital-data-converter',
        category: 'converters',
        icon: '💾',
        description: 'Convert between Bytes, KB, MB, GB, and TB.',
        keywords: ['bytes', 'kb', 'mb', 'data', 'unit'],
        module: () => import('./tools/converters/digital-data-converter'),
    },
];

export function getToolBySlug(slug: string): ToolEntry | undefined {
    return tools.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: string): ToolEntry[] {
    if (category === 'all') return tools;
    return tools.filter((t) => t.category === category);
}

export function searchTools(query: string): ToolEntry[] {
    const q = query.toLowerCase().trim();
    if (!q) return tools;
    return tools.filter(
        (t) =>
            t.name.toLowerCase().includes(q) ||
            t.description.toLowerCase().includes(q) ||
            t.keywords.some((k) => k.includes(q))
    );
}
